### Problem 1

### 1.a

Write a function dot_product to calculate the dot product of two 1 X n arrays, for emample:

a = array([1, 2, 3, 4])<br>
b = array([2, 3, 4, 5])

1 X 2 = 2<br>
2 X 3 = 6<br>
3 X 4 = 12<br>
4 X 5 = 20

2 + 6 + 12 + 20 = 40

dot_product (a, b) = 40

### Answer

In [9]:
def dot_product(a, b):
    return np.sum(a*b)

### Test

In [26]:
# Firts of all lets import numpy 
import numpy as np

# Create two arrays using numpy 
a = np.array([1, 2, 3, 4])
b = np.array([2, 3, 4, 5])

# Now lets call our function to test it, expecting the return to be 40
dot_product(a, b)

40

### 1.b

Given a 1 X n array, write a function odd(a) to return elements of the array whose index are odd numbers, for example:

a = np.array([1, 4, 7, 2, 7, 8, 5, 4, 9])<br>
odd(a) = np.array([4, 2, 8, 4])

### Answer

In [27]:
def odd(a):
    
    # Get all the indices of a from 0 to n using np.arange 
    index = np.arange(len(a))
    
    # Eliminate all the pair indices of a using the modulo
    index = index[index%2!=0]
    
    # Return all the elements of a with odd indices 
    return a[index]    

### Test

In [28]:
# Create an array using numpy 
a = np.array([1, 4, 7, 2, 7, 8, 5, 4, 9])

# Now lets call our function to test it, expecting the return to be array([4, 2, 8, 4])
odd(a)

array([4, 2, 8, 4])

### Problem 2

For 2.a - 2.d, you should construct the arrays without listing the elements, for example: you should use np.ones(3) to get array([1, 1, 1]) instead of using np.array([1, 1, 1])

### 2.a

Create an array of floats from 0 - 10, for example:

array[(0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 10.)]

### Answer

In [30]:
np.arange(11.)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### 2.b

Create an array containing seven equally spaced numbers between 0 and 23

### Answer

In [31]:
np.linspace(0, 23, 7)

array([ 0.        ,  3.83333333,  7.66666667, 11.5       , 15.33333333,
       19.16666667, 23.        ])

### 2.c

Create a 3 X 3 matrix with values ranging from 0 to 8

### Answer


In [65]:
# First lets make an array of the numbers ranging from 0 to 8
array = np.arange(0, 9)

# Lets see it
print(array)

# Print some stars to separate
print('*'*50)

# Now lets reshape this array to become a 3 X 3 Matrix
matrix = array.reshape(3, 3)

# Lets see it
print(matrix)

[0 1 2 3 4 5 6 7 8]
**************************************************
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### 2.d

Create a 5 X 5 matrix with row values ranging from 0 to 4

### Answer

In [69]:
# Lets start by making a 5 X 5 matrix of zeros, make sure we change the data type of all elements to integer
matrix = np.zeros([5, 5], dtype = np.int) 

# Lets see it
print(matrix)

# Print some stars to separate
print('*'*50)

# Now lets add an array of values from 0 to 4 to each one of the rows of the matrix
matrix = matrix + np.arange(0, 5)

# Lets see it
print(matrix)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
**************************************************
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


### 2.e

A magic square is a matrix all of whose row sums, column sums and the sums of the two diagonals are the same. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonal goes from top right to bottom left.)

A $n * n$ magic matrix is constructed by $(1, 2, 3... n^2)$, for example, here is a 3 X 3 magic matrix.

$\left[
\begin{array}{cc}
8 & 1 & 6 \\
3 & 5 & 7 \\
4 & 9 & 2
\end{array}
\right]$

Each number can only be used once.

Write a function IsMagic(x) to check whether a matrix is a magic matrix. You should check these three properties:

First, is it a square matrix?<br>
Second, is it constructed by $(1, 2, 3, ... n^2)$?<br>
Third, are the sums of rows, columns and diags the same? (Hint: the function **np.diag** may be useful)

### Answer

In [128]:
def IsMagic(x):
    
    # Lets start by checking if the matrix is a square by checking
    # if the number of columns is the same as the number of rows
    row = x.shape[0]
    col = x.shape[1]
    if row != col:
        return 'NOT MAGIC, NOT EVEN A SQUARE'
    
    # Okay now lets check if it consists of (1,2,3,...n2) by comparing it 
    # to an aranged version of the number of values of the matrix. 
    
    # Lets start by converting our matrix into an array
    arr = x.reshape(row * col)
    
    # Now lets use set to arrange our values and delete repeter ones then compare it to 
    # an array of values 0 to n^2
    if set(arr) != set(np.arange(1, row*col+1)):
        return 'NOT MAGIC, SOME NUMBERS ARE REPEATED ;/'
    
    # Okay lets see if all rows, columns and diagonals add up to the same
    # Get sum of all columns
    colsum = np.sum(x, 0)
    
    # Get sum of all rows
    rowsum = np.sum(x, 1)
    
    # Get sum of one diagonal
    diagsum = np.sum(np.diag(x))
    
    # Get sum of other diagonal
    diagsum2 = np.sum(np.diag(x[:, ::-1]))
    
    # Now that we have all sums lets see if they are all the same
    if all(colsum == diagsum) and all(rowsum == diagsum) and diagsum == diagsum2:
        return 'YES!! ITS MAGICAL'
    else:
        return 'NOT MAGIC, THE SUMS ARE NOT ALL THE SAME ;/'
    

### Test

In [141]:
test1 = np.array([[0, 1], 
                  [1, 0]])

# This should be False
IsMagic(test1) 

'NOT MAGIC, SOME NUMBERS ARE REPEATED ;/'

In [146]:
test2 = np.array([[8, 1, 6],
                  [3, 5, 7],
                  [4, 9, 2]])

# This should be True
IsMagic(test2)

'YES!! ITS MAGICAL'

In [142]:
test22 = np.array([[8, 1, 6],
                  [3, 5, 7]])

# This should be False
IsMagic(test22)

'NOT MAGIC, NOT EVEN A SQUARE'

In [140]:
test3 = np.array([[2, 6, 7],
                  [4, 8, 3],
                  [9, 1, 5]])

# This should be False
IsMagic(test3)

'NOT MAGIC, THE SUMS ARE NOT ALL THE SAME ;/'

In [145]:
test4 = np.array([[16, 2, 3, 13],
                  [5, 11, 10, 8],
                  [9,  7, 6, 12],
                  [4, 14, 15, 1]]) 

# This should be True
IsMagic(test4)

'YES!! ITS MAGICAL'

In [144]:
test5 = np.array([[17, 24,  1,  8, 15],
                  [23,  5,  7, 14, 16],
                  [4,   6, 13, 20, 22],
                  [10, 12, 19, 21,  3],
                  [11, 18, 25, 2,   9]])

# This should be True
IsMagic(test5)

'YES!! ITS MAGICAL'

In [143]:
test6 = np.array([[35, 1, 6, 26, 19, 24],
                  [3, 32, 7, 21, 23, 25],
                  [31, 9, 2, 22, 27, 20],
                  [8, 28, 33, 17, 10,15],
                  [30, 5, 34, 12, 14,16],
                  [4, 36, 29, 13, 18,11]])

# This should be True
IsMagic(test6)

'YES!! ITS MAGICAL'